### ISSUE TITLE
Low Fidelity Wireframes

### ISSUE THREAD

**Issue by mjkern** [hvk5388/My-Personal-Website#3]
Create lo fi wireframes for your personal website.

If you refer to online examples, please link them in this issue.

**Comment by hvk5388** [comment]
Minimalist, bold colors:
http://annaellenberger.com/
http://www.roxanegay.com/

Individual, nice signature:
https://charlimarie.com/

Accessible icons:
https://jonmiron.com/

Easy menu, good use of icons:
https://www.ajafrost.com/

Concise, easy to read:
http://martinboeh.me/

Moving icons, good use of images:
 https://calvinhklui.com/

Inviting, good scrolling:
http://www.christiechong.net/#intro

Simple, fun menu:
http://www.natalie-harmon.com/
