### ISSUE TITLE
User Test Wireframes

### ISSUE THREAD

**Issue by mjkern** [hvk5388/My-Personal-Website#5]
Show your wireframes to at least 2-4 people and get their feedback. Use good user testing practices (no leading questions, etc).

Record feedback and make any appropriate updates to wireframes.

**Comment by hvk5388** [comment]
Both becca and mother were confused about the scrolling, but that was probably due to the fact it was on paper. Mom had concerns about the wording, but that is a work in progress

**Comment by mjkern** [comment]
Okay, I agree that it will probably make more sense live. Maybe showing them an example would work. Not sure if figma would let you do somthing like that if you made interactive wrieframes...
