### ISSUE TITLE
Higher Fidelity Wireframes

### ISSUE THREAD

**Issue by mjkern** [hvk5388/My-Personal-Website#7]
Create mid/high fidelity wireframes. User test and iterate a needed. Record any feedback.

Work on an appropriate branch and create a pr (pull request) when complete.

**Comment by hvk5388** [comment]
https://www.figma.com/file/jV2bouqVvdLgGprpL8xyyN/My-Personal-Website?node-id=0%3A1

This is my wireframe. I received a lot of positive feedback. The color scheme fits nicely. The pictures were not specifically professional, but I was not under the impression that was necessary. i was unsure about my name in the top corner. it could be a signature too. i also had trouble getting icons for the contact page

**Comment by mjkern** [comment]
Nice work Hannah, these look great!

A few things:
- I love the first image!
- Can you put a filler for at least one of your work/projects things so I can see how the font/title will look and if there will be images for them?
- Will your work section have a heading?
- You can always change up the name later, but I think this text is nice
- I use [flaticon](https://www.flaticon.com/) usually for my icons. You will probably have to include a referce to the person who made them at the bottom though
- Would you also include a link to your linked in? Any others?
- Is "work" what you want to call it? Would projects or experience be more appropriate?
- Interesting that you capitalize "Let's Chat!" but not the other stuff. I don't think this looks bad, just interesting
- Nice job on the interactive wireframes. I would probably have your name in the top left link back to the very top (home screen) but the wireframes need not reflect this

**Comment by mjkern** [comment]
Also, did you recieve any negative feedback? This is usually most valuable

**Comment by mjkern** [comment]
@hvk5388 Nice updates. Minor questions:
- Can you remove the extra icons on the bottom right of the works page?
- Have you considered a somewhat transparent nav bar?
