### ISSUE TITLE
Go Live!

### ISSUE THREAD

**Issue by mjkern** [hvk5388/My-Personal-Website#9]
Host your website by changing your github settings for github pages.

Note that sometimes changes to the live site take a few minutes to show up.

**Comment by mjkern** [comment]
Can you attach the link to the live site here (because I don't see your settings)

**Comment by hvk5388** [comment]
https://hvk5388.github.io/My-Personal-Website/

**Comment by mjkern** [comment]
Nice job! It is live :)
